[FIX] Partially revert a83b66705e6d49ce33293c7b7164bd440da255b1
+ Signature of function in inherited model doesn't match parent class
function signature. Code broken because of:

TypeError: _partial_move_for() got an unexpected keyword argument
'context'