stock_picking_package_preparation_line: rename product_uom_id
FIX stock_picking_package_preparation_line : Field `product_uom` does not exist

FIX stock_picking_package_preparation_line: AttributeError: 'stock.move' object has no attribute 'product_uom_id'